### ISSUE TITLE
update Holdings endpoint and replace "address" with "vaultAddress"

### ISSUE THREAD

**Issue by miguel567** [iearn-finance/yearn-api#36]

**Comment by miguel567** [comment]
@x48-crypto I tried updating to vaultAddress, but I have to update the resource.loca.yml:

BEFORE
```
      KeySchema:
        - AttributeName: address
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: address
          AttributeType: S
```

AFTER
```
      KeySchema:
        - AttributeName: vaultAddress
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: vaultAddress
          AttributeType: S
```

by doings this it will work as you request, BUT: in the HOLDINGS endpoint I store the Vaults Holdings, Strategy Holdings and also, the YFI staked in GOV (not a real vault) and the veCRV locked (not a real vault). HENCE, I suggest to not execute this issue as it would be misleading "address" is more generic and would be correct for naming the address of YFI staked and veCRV.
